"""Linking effectome dynamics to behavior (Stage 6): stats, decoding, lead-lag."""

from .alignment import (
    LeadLagResult,
    activity_magnitude_features,
    change_signal,
    combined_continuity_groups,
    future_manifold_displacement,
    lead_lag,
    manifold_speed,
    manifold_velocity,
)
from .comparison import EffectomeAgreement, SignedEffectomeScaler, signed_effectome_agreement
from .decoding import (
    DecodeResult,
    DependencySupport,
    IncrementalDecodeResult,
    anchor_continuity_labels,
    anchor_dependency_intervals,
    anchor_group_labels,
    community_features,
    community_reconfiguration_features,
    connectivity_features,
    decode_behavior,
    incremental_decode_behavior,
    purged_blocked_splits,
    state_features,
    valid_positive_lag_origins,
)
from .stats import (
    AssociationResult,
    ConfidenceInterval,
    association_with_null,
    benjamini_hochberg,
    block_shuffle_null,
    bootstrap_mean_ci,
    circular_shift_null,
    partition_stability,
    state_behavior_mi,
)

__all__ = [
    "AssociationResult",
    "ConfidenceInterval",
    "DependencySupport",
    "EffectomeAgreement",
    "DecodeResult",
    "IncrementalDecodeResult",
    "LeadLagResult",
    "SignedEffectomeScaler",
    "activity_magnitude_features",
    "combined_continuity_groups",
    "anchor_dependency_intervals",
    "anchor_continuity_labels",
    "anchor_group_labels",
    "association_with_null",
    "benjamini_hochberg",
    "block_shuffle_null",
    "bootstrap_mean_ci",
    "change_signal",
    "circular_shift_null",
    "community_features",
    "community_reconfiguration_features",
    "connectivity_features",
    "decode_behavior",
    "incremental_decode_behavior",
    "lead_lag",
    "future_manifold_displacement",
    "manifold_speed",
    "manifold_velocity",
    "partition_stability",
    "purged_blocked_splits",
    "state_behavior_mi",
    "state_features",
    "signed_effectome_agreement",
    "valid_positive_lag_origins",
]
